module.exports = [
  {
    "id": 1,
    "subject": "Le passage de Lorem Ipsum standard, utilisé depuis 1500",
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "link": "",
    "payload": "{}",
    "payload_json": "{}",
    "source_id": 45,
    "type_id": 63,
    "channel": null,
    "priority": 1,
    "icon": "fa-comment",
    "color": "#ff0000",
    "tags": "",
    "note": null,
    "status": "PUBLISHED",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-03-04T07:42:54.000Z",
    "created_by": 1,
    "updated_at": "2016-06-17T16:02:34.000Z",
    "updated_by": 1
  },
  {
    "id": 2,
    "subject": "Section 1.10.32 du \"De Finibus Bonorum et Malorum\" de Ciceron (45 av. J.-C.)",
    "body": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 45,
    "type_id": 63,
    "channel": null,
    "priority": 1,
    "icon": "fa-comments",
    "color": "#00ff00",
    "tags": null,
    "note": null,
    "status": "PUBLISHED",
    "ack_at": null,
    "expired_at": "2016-05-27T16:21:44.000Z",
    "created_at": "2016-03-04T07:42:54.000Z",
    "created_by": 1,
    "updated_at": "2016-03-04T07:43:12.000Z",
    "updated_by": 1
  },
  {
    "id": 3,
    "subject": "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...",
    "body": "Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec ut dolor et mi lobortis venenatis. Morbi fermentum, tortor ut porttitor ultrices, eros mi euismod magna, sed malesuada lectus orci ut magna. Integer euismod ornare turpis, et fermentum diam volutpat et. Quisque commodo leo vitae urna laoreet iaculis. Mauris arcu dui, scelerisque pretium molestie at, fringilla et felis. Donec sed dictum magna. Pellentesque vulputate porta nulla. Ut mi velit, fermentum in ex sed, scelerisque semper dolor. Fusce eget augue in tortor pulvinar aliquam. Donec elementum nibh ac lobortis consequat. Ut tristique purus sit amet odio maximus dignissim. Aenean quis ipsum suscipit, accumsan risus sed, volutpat justo. Quisque sed condimentum tortor. Etiam vitae imperdiet dolor. Integer rutrum sodales sapien quis congue.",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 45,
    "type_id": 63,
    "channel": null,
    "priority": 1,
    "icon": "fa-cloud",
    "color": "#ffd966",
    "tags": null,
    "note": null,
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": "2016-05-27T16:21:44.000Z",
    "created_at": "2016-03-04T07:42:54.000Z",
    "created_by": 1,
    "updated_at": "2016-05-28T09:43:40.000Z",
    "updated_by": 1
  },
  {
    "id": 4,
    "subject": "1 paragraphes, 25 mots, 177 caractères de Lorem Ipsum généré",
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam hendrerit elit in magna tristique lobortis. Sed quis libero maximus, sagittis odio vitae, porttitor mauris. Morbi.",
    "link": "http://fr.lipsum.com/feed/html",
    "payload": null,
    "payload_json": null,
    "source_id": 43,
    "type_id": 63,
    "channel": null,
    "priority": 5,
    "icon": "fa-certificate",
    "color": "#00ffff",
    "tags": "",
    "note": null,
    "status": "PUBLISHED",
    "ack_at": null,
    "expired_at": "2017-05-27T16:21:44.000Z",
    "created_at": "2016-03-04T07:42:54.000Z",
    "created_by": 1,
    "updated_at": "2016-05-28T12:35:51.000Z",
    "updated_by": 1
  },
  {
    "id": 5,
    "subject": "One more for the road",
    "body": "Getting tired",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 45,
    "type_id": 63,
    "channel": null,
    "priority": null,
    "icon": "fa-database",
    "color": "#ff0000",
    "tags": null,
    "note": null,
    "status": "PUBLISHED",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-03-03T17:29:43.000Z",
    "created_by": 1,
    "updated_at": "2016-03-03T17:37:34.000Z",
    "updated_by": 1
  },
  {
    "id": 6,
    "subject": "SN 123 Landed",
    "body": "SN123 from Alicante landed with 34 minutes delay",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 45,
    "type_id": 49,
    "channel": null,
    "priority": 2,
    "icon": "",
    "color": "",
    "tags": null,
    "note": "Buffer In on landing tracks",
    "status": "ACTIVE",
    "ack_at": null,
    "expired_at": "2016-05-28T08:20:00.000Z",
    "created_at": "2016-05-27T16:21:44.000Z",
    "created_by": 1,
    "updated_at": "2016-05-27T16:21:44.000Z",
    "updated_by": 1
  },
  {
    "id": 7,
    "subject": "SN 234 Push Back",
    "body": "SN234 pushed back for taxi.",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 45,
    "type_id": 50,
    "channel": null,
    "priority": 2,
    "icon": "",
    "color": "",
    "tags": null,
    "note": "Buffer In out parking or detection of movement.",
    "status": "ACTIVE",
    "ack_at": null,
    "expired_at": "2016-05-28T08:20:00.000Z",
    "created_at": "2016-05-27T16:22:33.000Z",
    "created_by": 1,
    "updated_at": "2016-05-27T16:22:33.000Z",
    "updated_by": 1
  },
  {
    "id": 8,
    "subject": "Average delay 2 minutes",
    "body": "Average delay on last 4 hours is 2 minutes. Landing delay: -3 minutes, departure delay: +12 minutes.",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 43,
    "type_id": 51,
    "channel": null,
    "priority": 1,
    "icon": "",
    "color": "#00ff00",
    "tags": null,
    "note": "Buffer In out parking or detection of movement.",
    "status": "ACTIVE",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-05-27T16:23:46.000Z",
    "created_by": 1,
    "updated_at": "2016-05-28T12:31:39.000Z",
    "updated_by": 1
  },
  {
    "id": 9,
    "subject": "Average delay 25 minutes",
    "body": "Average delay on last 4 hours is 2 minutes. Landing delay: 15 minutes, departure delay: +24 minutes.",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 43,
    "type_id": 51,
    "channel": null,
    "priority": 1,
    "icon": "",
    "color": "",
    "tags": null,
    "note": "Buffer In out parking or detection of movement.",
    "status": "ACTIVE",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-05-27T16:24:24.000Z",
    "created_by": 1,
    "updated_at": "2016-05-27T16:24:24.000Z",
    "updated_by": 1
  },
  {
    "id": 10,
    "subject": "Metar EBLG 30 04:50Z 06:50L",
    "body": "EBLG 300450Z 34007KT 1600 RA BR FEW002 BKN003 15/13 Q1005 TEMPO 1200 RADZ BKN002",
    "link": "http://weather.noaa.gov/pub/data/observations/metar/stations/EBLG.TXT",
    "payload": null,
    "payload_json": null,
    "source_id": 45,
    "type_id": 48,
    "channel": null,
    "priority": 3,
    "icon": "fa-sun-o",
    "color": "",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-05-30T05:27:05.000Z",
    "created_by": 1,
    "updated_at": "2016-06-07T15:18:50.000Z",
    "updated_by": 1
  },
  {
    "id": 11,
    "subject": "QFU Changed to 23 L/R",
    "body": "{\"value\": \"23\", \"note\": \"L/R\"}",
    "link": "",
    "payload": "{\"value\": \"23\", \"note\": \"L/R\"}",
    "payload_json": "{\"note\": \"L/R\", \"value\": \"23\"}",
    "source_id": 43,
    "type_id": 55,
    "channel": null,
    "priority": 4,
    "icon": "fa-plane",
    "color": "#4a86e8",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-01T20:55:03.000Z",
    "created_by": 1,
    "updated_at": "2016-06-01T21:06:55.000Z",
    "updated_by": 1
  },
  {
    "id": 12,
    "subject": "QFU Changed to 05 L/R",
    "body": "{\"value\": \"05\", \"note\": \"L / R\"}",
    "link": "",
    "payload": "{\"value\": \"05\", \"note\": \"L / R\"}",
    "payload_json": "{\"note\": \"L / R\", \"value\": \"05\"}",
    "source_id": 43,
    "type_id": 55,
    "channel": null,
    "priority": 4,
    "icon": "fa-plane",
    "color": "#4a86e8",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-01T20:55:14.000Z",
    "created_by": 1,
    "updated_at": "2016-06-07T11:46:13.000Z",
    "updated_by": 1
  },
  {
    "id": 13,
    "subject": "Flight SN123 at outer marker",
    "body": "{\"marker\":\"outer\"}",
    "link": "",
    "payload": "{\"marker\":\"outer\"}",
    "payload_json": "{\"marker\": \"outer\"}",
    "source_id": 45,
    "type_id": 60,
    "channel": 1,
    "priority": 3,
    "icon": "",
    "color": "#0000ff",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-02T06:03:55.000Z",
    "created_by": 1,
    "updated_at": "2016-06-06T06:22:11.000Z",
    "updated_by": 1
  },
  {
    "id": 14,
    "subject": "Middle Marker",
    "body": "{\"marker\":\"middle\"}",
    "link": "",
    "payload": "{\"marker\":\"middle\"}",
    "payload_json": "{\"marker\": \"middle\"}",
    "source_id": 45,
    "type_id": 60,
    "channel": 2,
    "priority": 4,
    "icon": "",
    "color": "#f1c232",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-02T06:04:13.000Z",
    "created_by": 1,
    "updated_at": "2016-06-06T06:43:46.000Z",
    "updated_by": 1
  },
  {
    "id": 15,
    "subject": "Inner Marker",
    "body": "{\"marker\": \"inner\"}",
    "link": "",
    "payload": "{\"marker\": \"inner\"}",
    "payload_json": "{\"marker\": \"inner\"}",
    "source_id": 45,
    "type_id": 60,
    "channel": 2,
    "priority": 5,
    "icon": "",
    "color": "#ffffff",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-02T06:04:26.000Z",
    "created_by": 1,
    "updated_at": "2016-06-06T06:44:10.000Z",
    "updated_by": 1
  },
  {
    "id": 16,
    "subject": "Arrivals",
    "body": "[{\"registration\":\"OO-123\",\"flight_number\":\"SN 123\",\"destination\":\"Alicante\",\"schedule\":\"14:30\",\"estimated\":\"15:10\",\"actual\":\"-\",\"delay\":\"40\"},{\"registration\":\"F-4321\",\"flight_number\":\"AF 456\",\"destination\":\"Orly\",\"schedule\":\"15:00\",\"estimated\":\"15:00\",\"actual\":\"-\",\"delay\":\"0\"}]",
    "link": "",
    "payload": "[{\"registration\":\"OO-123\",\"flight_number\":\"SN 123\",\"destination\":\"Alicante\",\"schedule\":\"14:30\",\"estimated\":\"15:10\",\"actual\":\"-\",\"delay\":\"40\"},{\"registration\":\"F-4321\",\"flight_number\":\"AF 456\",\"destination\":\"Orly\",\"schedule\":\"15:00\",\"estimated\":\"15:00\",\"actual\":\"-\",\"delay\":\"0\"}]",
    "payload_json": "[{\"delay\": \"40\", \"actual\": \"-\", \"schedule\": \"14:30\", \"estimated\": \"15:10\", \"destination\": \"Alicante\", \"registration\": \"OO-123\", \"flight_number\": \"SN 123\"}, {\"delay\": \"0\", \"actual\": \"-\", \"schedule\": \"15:00\", \"estimated\": \"15:00\", \"destination\": \"Orly\", \"registration\": \"F-4321\", \"flight_number\": \"AF 456\"}]",
    "source_id": 43,
    "type_id": 61,
    "channel": null,
    "priority": null,
    "icon": "",
    "color": "",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-07T11:41:00.000Z",
    "created_by": 1,
    "updated_at": "2016-06-10T10:26:45.000Z",
    "updated_by": 1
  },
  {
    "id": 17,
    "subject": "Departures",
    "body": "[{\"registration\":\"OO-123\",\"flight_number\":\"SN 123\",\"destination\":\"Alicante\",\"schedule\":\"14:30\",\"estimated\":\"15:10\",\"actual\":\"-\",\"delay\":\"40\"},{\"registration\":\"F-4321\",\"flight_number\":\"AF 456\",\"destination\":\"Orly\",\"schedule\":\"15:00\",\"estimated\":\"15:00\",\"actual\":\"-\",\"delay\":\"0\"}]",
    "link": "",
    "payload": "[{\"registration\":\"OO-123\",\"flight_number\":\"SN 123\",\"destination\":\"Alicante\",\"schedule\":\"14:30\",\"estimated\":\"15:10\",\"actual\":\"-\",\"delay\":\"40\"},{\"registration\":\"F-4321\",\"flight_number\":\"AF 456\",\"destination\":\"Orly\",\"schedule\":\"15:00\",\"estimated\":\"15:00\",\"actual\":\"-\",\"delay\":\"0\"}]",
    "payload_json": "[{\"delay\": \"40\", \"actual\": \"-\", \"schedule\": \"14:30\", \"estimated\": \"15:10\", \"destination\": \"Alicante\", \"registration\": \"OO-123\", \"flight_number\": \"SN 123\"}, {\"delay\": \"0\", \"actual\": \"-\", \"schedule\": \"15:00\", \"estimated\": \"15:00\", \"destination\": \"Orly\", \"registration\": \"F-4321\", \"flight_number\": \"AF 456\"}]",
    "source_id": 43,
    "type_id": 62,
    "channel": null,
    "priority": null,
    "icon": "",
    "color": "",
    "tags": null,
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-07T12:24:15.000Z",
    "created_by": 1,
    "updated_at": "2016-06-07T12:24:15.000Z",
    "updated_by": 1
  },
  {
    "id": 18,
    "subject": "New news for Liège Airport",
    "body": "New news for Liège Airport",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 45,
    "type_id": 64,
    "channel": null,
    "priority": 2,
    "icon": "fa-comment-o",
    "color": "#ff9900",
    "tags": null,
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-07T15:03:23.000Z",
    "created_by": 1,
    "updated_at": "2016-06-07T15:03:23.000Z",
    "updated_by": 1
  },
  {
    "id": 19,
    "subject": "Sample NOTAM",
    "body": "A1234/06 NOTAMR A1212/06\r\nQ)EGTT/QMXLC/IV/NBO/A/000/999/5129N00028W005\r\nA)EGLL\r\nB)0609050500\r\nC)0704300500\r\nE)DUE WIP TWY B SOUTH CLSD BTN 'F' AND 'R'. TWY 'R' CLSD BTN 'A' AND 'B' AND DIVERTED VIA NEW GREEN CL AND BLUE EDGE LGT. CTN ADZ",
    "link": "",
    "payload": null,
    "payload_json": null,
    "source_id": 43,
    "type_id": 65,
    "channel": null,
    "priority": 1,
    "icon": "",
    "color": "accent",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-08T05:16:08.000Z",
    "created_by": 1,
    "updated_at": "2016-06-08T05:23:00.000Z",
    "updated_by": 1
  },
  {
    "id": 20,
    "subject": "Parking occupancy change",
    "body": "",
    "link": "",
    "payload": "{\"pax\":{\"busy\":7,\"avail\":15},\"freit\":{\"busy\":2,\"avail\":21}}",
    "payload_json": "{\"pax\": {\"busy\": 7, \"avail\": 15}, \"freit\": {\"busy\": 2, \"avail\": 21}}",
    "source_id": 43,
    "type_id": 52,
    "channel": null,
    "priority": null,
    "icon": "",
    "color": "",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-10T13:21:28.000Z",
    "created_by": 1,
    "updated_at": "2016-06-10T13:35:45.000Z",
    "updated_by": 1
  },
  {
    "id": 21,
    "subject": "Parking occupancy change",
    "body": "",
    "link": "",
    "payload": "{\"pax\":{\"busy\":8,\"avail\":14},\"freit\":{\"busy\":2,\"avail\":21}}",
    "payload_json": "{\"pax\": {\"busy\": 8, \"avail\": 14}, \"freit\": {\"busy\": 2, \"avail\": 21}}",
    "source_id": 43,
    "type_id": 52,
    "channel": null,
    "priority": null,
    "icon": "",
    "color": "",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-10T13:21:28.000Z",
    "created_by": 1,
    "updated_at": "2016-06-10T13:35:45.000Z",
    "updated_by": 1
  },
  {
    "id": 22,
    "subject": "Delay report",
    "body": "",
    "link": "",
    "payload": "[{\"code\":\"02\",\"reason\":\"Weather\",\"time\":7870,\"percent\":44},{\"code\":\"03\",\"reason\":\"ATC Capacity\",\"time\":5192,\"percent\":29},{\"code\":\"03\",\"reason\":\"Aerodrome Capacity\",\"time\":1573,\"percent\":9}]",
    "payload_json": "[{\"code\": \"02\", \"time\": 7870, \"reason\": \"Weather\", \"percent\": 44}, {\"code\": \"03\", \"time\": 5192, \"reason\": \"ATC Capacity\", \"percent\": 29}, {\"code\": \"03\", \"time\": 1573, \"reason\": \"Aerodrome Capacity\", \"percent\": 9}]",
    "source_id": 43,
    "type_id": 51,
    "channel": null,
    "priority": null,
    "icon": "",
    "color": "",
    "tags": null,
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-10T13:52:49.000Z",
    "created_by": 1,
    "updated_at": "2016-06-10T13:52:49.000Z",
    "updated_by": 1
  },
  {
    "id": 23,
    "subject": "Complex text with variable substitution",
    "body": "Here is some text to be replaced: {{payload.a_number}} {{payload.a_string}} hits on {{payload.a_date}}.",
    "link": "",
    "payload": "{\"a_number\":12,\"a_string\":\"ducks\",\"a_date\":\"19970716T1920+0100\"}",
    "payload_json": "{\"a_date\": \"19970716T1920+0100\", \"a_number\": 12, \"a_string\": \"ducks\"}",
    "source_id": 45,
    "type_id": 63,
    "channel": null,
    "priority": 1,
    "icon": "fa-ellipsis-h",
    "color": "#ff0000",
    "tags": "",
    "note": "Testing substitution",
    "status": "ACTIVE",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-15T08:24:53.000Z",
    "created_by": 1,
    "updated_at": "2016-06-16T05:22:10.000Z",
    "updated_by": 1
  },
  {
    "id": 24,
    "subject": "GIP Notification Sample",
    "body": "This notification sends an SMS to {{payload.notification.parameters.phone_number}}.",
    "link": "",
    "payload": "{\"name\":\"Rule Name\",\"notification\":{\"name\":\"Send SMS\",\"timestamp\":\"20160324143258.635Z\",\"parameters\":{\"phone_number\":\"+321234567890\"}},\"detection\":{\"name\":\"BUFFER_IN\",\"parameters\":{\"zone_group\":\"Parkings\"}},\"triggers\":{\"zone\":{\"name\":\"P52\",\"display_name\":\"Parking 52\",\"type\":\"PARKING\",\"display_status\":\"\",\"status\":\"ACTIVE\"},\"device\":{\"name\":\"00:43:56:78:9A\",\"display_name\":\"Tetra #42\",\"type\":\"TETRA\",\"display_status\":\"\",\"status\":\"ACTIVE\"}},\"input\":{\"provider\":\"TETRA_DATABASE\",\"device_key\":\"00:43:56:78:9A\",\"latitude\":50.52,\"longitude\":5.67,\"altitude\":10600,\"timestamp\":\"20160420092838.723L\",\"original\":{\"type\":\"tetra\",\"maca\":\"00:43:56:78:9A\",\"phone\":\"+3245551234\",\"lat\":50.52,\"lon\":5.67,\"alt\":10600,\"name\":\"Oscar Dubois\",\"ts\":\"20160420092837.502L\"}}}",
    "payload_json": "{\"name\": \"Rule Name\", \"input\": {\"altitude\": 10600, \"latitude\": 50.52, \"original\": {\"ts\": \"20160420092837.502L\", \"alt\": 10600, \"lat\": 50.52, \"lon\": 5.67, \"maca\": \"00:43:56:78:9A\", \"name\": \"Oscar Dubois\", \"type\": \"tetra\", \"phone\": \"+3245551234\"}, \"provider\": \"TETRA_DATABASE\", \"longitude\": 5.67, \"timestamp\": \"20160420092838.723L\", \"device_key\": \"00:43:56:78:9A\"}, \"triggers\": {\"zone\": {\"name\": \"P52\", \"type\": \"PARKING\", \"status\": \"ACTIVE\", \"display_name\": \"Parking 52\", \"display_status\": \"\"}, \"device\": {\"name\": \"00:43:56:78:9A\", \"type\": \"TETRA\", \"status\": \"ACTIVE\", \"display_name\": \"Tetra #42\", \"display_status\": \"\"}}, \"detection\": {\"name\": \"BUFFER_IN\", \"parameters\": {\"zone_group\": \"Parkings\"}}, \"notification\": {\"name\": \"Send SMS\", \"timestamp\": \"20160324143258.635Z\", \"parameters\": {\"phone_number\": \"+321234567890\"}}}",
    "source_id": 45,
    "type_id": 63,
    "channel": null,
    "priority": 1,
    "icon": "fa-child",
    "color": "",
    "tags": "",
    "note": "",
    "status": "ACTIVE",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-16T14:24:06.000Z",
    "created_by": 1,
    "updated_at": "2016-06-26T15:46:39.000Z",
    "updated_by": 1
  },
  {
    "id": 25,
    "subject": "Big mustache",
    "body": "Testing mustache:\r\n{{#payload.musketeers}}\r\n* {{.}}\r\n{{/payload.musketeers}}",
    "link": "",
    "payload": "{\"musketeers\":[\"Athos\",\"Aramis\",\"Porthos\",\"D'Artagnan\"]}",
    "payload_json": "{\"musketeers\": [\"Athos\", \"Aramis\", \"Porthos\", \"D'Artagnan\"]}",
    "source_id": 45,
    "type_id": 63,
    "channel": null,
    "priority": 2,
    "icon": "",
    "color": "",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-06-26T16:01:34.000Z",
    "created_by": 1,
    "updated_at": "2016-06-26T16:09:25.000Z",
    "updated_by": 1
  },
  {
    "id": 26,
    "subject": "Sample GeoJSON payload",
    "body": "Sample geojson payload for testing.",
    "link": "",
    "payload": "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[102,0.5]},\"properties\":{\"prop0\":\"value0\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"LineString\",\"coordinates\":[[102,0],[103,1],[104,0],[105,1]]},\"properties\":{\"prop0\":\"value0\",\"prop1\":0}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[100,0],[101,0],[101,1],[100,1],[100,0]]]},\"properties\":{\"prop0\":\"value0\",\"prop1\":{\"this\":\"that\"}}}]}",
    "payload_json": "{\"type\": \"FeatureCollection\", \"features\": [{\"type\": \"Feature\", \"geometry\": {\"type\": \"Point\", \"coordinates\": [102, 0.5]}, \"properties\": {\"prop0\": \"value0\"}}, {\"type\": \"Feature\", \"geometry\": {\"type\": \"LineString\", \"coordinates\": [[102, 0], [103, 1], [104, 0], [105, 1]]}, \"properties\": {\"prop0\": \"value0\", \"prop1\": 0}}, {\"type\": \"Feature\", \"geometry\": {\"type\": \"Polygon\", \"coordinates\": [[[100, 0], [101, 0], [101, 1], [100, 1], [100, 0]]]}, \"properties\": {\"prop0\": \"value0\", \"prop1\": {\"this\": \"that\"}}}]}",
    "source_id": 45,
    "type_id": 67,
    "channel": null,
    "priority": null,
    "icon": "",
    "color": "",
    "tags": "",
    "note": "",
    "status": "UNREAD",
    "ack_at": null,
    "expired_at": null,
    "created_at": "2016-07-04T09:51:57.000Z",
    "created_by": 1,
    "updated_at": "2016-07-04T09:54:44.000Z",
    "updated_by": 1
  }
]